# Generated by Django 4.1.1 on 2022-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_img',
            field=models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to='images/'),
            preserve_default=b'I01\n',
        ),
    ]
