# Generated by Django 4.1.1 on 2022-10-26 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_dal_roti_sabji_rename_hotel_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roti',
            name='price',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Userdetails1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=220)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
