# Generated by Django 4.1.1 on 2022-10-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_roti_price_userdetails1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dal',
            name='price',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sabji',
            name='price',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
    ]
